### ISSUE TITLE
Could highland.js be used?

### ISSUE THREAD

**Issue by amccloud** [milankinen/ffux#5]
I only ask because I know it is growing in popularity.

**Comment by amccloud** [comment]
Or Kefir https://github.com/rpominov/kefir

**Comment by milankinen** [comment]
Does highland have any stream combination function such as https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md? I didn't find it from the docs. It's mandatory when building the state object.

Kefir has a `combine` function so it could be supported.

**Comment by xgrommx** [comment]
@milankinen you can look on this https://github.com/rpominov/kefir/blob/master/test/perf/memory-specs/combine.coffee#L2

**Comment by milankinen** [comment]
Created new ticket for Kefir: #9 

Closing this one since highland.js has no functionality that supports stream combining
