### ISSUE TITLE
Source Code Documentation

### ISSUE THREAD

**Issue by dqdinh** [milankinen/ffux#6]
What do you think about documenting the source code? It would make understanding the source and contributing to it easier. Thanks.

**Comment by milankinen** [comment]
It's unfortunate that the code does not document itself. It means I've done something wrong... :-/

In general, I don't believe in fine-grained code documentation, but yeah - I should improve it a little bit. At least document the program flow.

**Comment by dqdinh** [comment]
Documenting the flow would help. Thanks.
